// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExecution(ctx context.Context, id uuid.UUID) error
	DeleteJob(ctx context.Context, arg DeleteJobParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetExecution(ctx context.Context, id uuid.UUID) (Execution, error)
	GetExecutionStats(ctx context.Context, jobID uuid.UUID) (GetExecutionStatsRow, error)
	GetExecutionsByJobID(ctx context.Context, jobID uuid.UUID) ([]Execution, error)
	GetExecutionsByJobIDWithLimit(ctx context.Context, arg GetExecutionsByJobIDWithLimitParams) ([]Execution, error)
	GetExecutionsByStatus(ctx context.Context, status ExecutionStatus) ([]Execution, error)
	GetJob(ctx context.Context, arg GetJobParams) (Job, error)
	GetJobCount(ctx context.Context, ownerID uuid.UUID) (int64, error)
	GetJobsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Job, error)
	GetJobsByOwnerWithLimit(ctx context.Context, arg GetJobsByOwnerWithLimitParams) ([]Job, error)
	GetPendingExecutions(ctx context.Context) ([]Execution, error)
	GetRecentJobs(ctx context.Context, arg GetRecentJobsParams) ([]Job, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserExecutionStats(ctx context.Context, ownerID uuid.UUID) (GetUserExecutionStatsRow, error)
	UpdateExecutionComplete(ctx context.Context, arg UpdateExecutionCompleteParams) (Execution, error)
	UpdateExecutionCostEstimate(ctx context.Context, arg UpdateExecutionCostEstimateParams) (Execution, error)
	UpdateExecutionScheduling(ctx context.Context, arg UpdateExecutionSchedulingParams) (Execution, error)
	UpdateExecutionStart(ctx context.Context, arg UpdateExecutionStartParams) (Execution, error)
	UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
